sonar.projectKey=softwareone-platform_swo-extension-playground
sonar.organization=softwareone-mpt-github

sonar.language=py

sonar.sources=backend/swo_playground
sonar.tests=backend/tests
sonar.inclusions=backend/swo_playground/**
sonar.exclusions=backend/tests/**,**/__init__.py

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3
